name: CI workflow

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: sergeevpasha/yandex-cloud-s3-sync-github-actions@v0.1.0
        with:
          YANDEX_CLOUD_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          YANDEX_CLOUD_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          YANDEX_CLOUD_BUCKET_NAME: ${{ secrets.S3_BUCKET }}
          PATH: "./static"
          CLEAR: true
