name: CI workflow

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clear
        uses: nantgrisha/ya-object-storage-website@v1.0.1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          bucket: ${{ secrets.S3_BUCKET }}
          path: "static"
          remove: true

      - name: Deploy
        uses: antgrisha/ya-object-storage-website@v1.0.1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          bucket: ${{ secrets.S3_BUCKET }}
          path: "static"
